//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.261
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaasOne.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaasOne.Properties.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd Time &amp; Price (Aft Mkt) ähnelt.
        /// </summary>
        internal static string after_mkt_price_and_time {
            get {
                return ResourceManager.GetString("after_mkt_price_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After Mkt Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_after_mkt_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_after_mkt_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After Mkt Chg &amp; % ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_after_mkt_change_and_percent {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_after_mkt_change_and_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aft Mkt % Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_after_mkt_percent_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_after_mkt_percent_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd (Aft Mkt) ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_after_mkt_price {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_after_mkt_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd Time (Aft Mkt) ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_after_mkt_time {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_after_mkt_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annualized Gain ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_annualized_gain {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_annualized_gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_ask_price {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_ask_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask Size ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_ask_size {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_ask_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg Vol ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_avg_daily_volume {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_avg_daily_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bid ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_bid_price {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_bid_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bid Size ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_bid_size {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_bid_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book Val ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_book_value {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_book_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chg &amp; % Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_change_and_percent {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_change_and_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chg 52-Wk Low ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_change_fiftytwo_week_high {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_change_fiftytwo_week_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chg 52-Wk High ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_change_fiftytwo_week_low {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_change_fiftytwo_week_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_comment {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commission ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_commission {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_currency {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day High ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_day_high {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_day_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day Low ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_day_low {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_day_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day&apos;s Low &amp; High ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_day_range {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_day_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day&apos;s Val Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_day_value_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_day_value_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day&apos;s Val Chg &amp; % ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_day_value_change_and_percent {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_day_value_change_and_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day&apos;s Val % Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_day_value_percent_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_day_value_percent_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ex-Div Date ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_dividend_pay_date {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_dividend_pay_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Div/Share ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_dividend_per_share {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_dividend_per_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yield ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_dividend_yield {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_dividend_yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EBITDA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_ebitda {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_ebitda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPS ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_eps {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_eps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPS Est Curr Yr ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_eps_est_current_year {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_eps_est_current_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPS Est Next Qtr ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_eps_est_next_quarter {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_eps_est_next_quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPS Est Next Yr ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_eps_est_next_year {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_eps_est_next_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ex-Div Date ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_ex_dividend_date {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_ex_dividend_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exchange ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_exchange {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 50-Day MA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_fifty_day_ma {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_fifty_day_ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chg from 50-Day MA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_fifty_day_ma_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_fifty_day_ma_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Chg from 50-Day MA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_fifty_day_ma_percent_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_fifty_day_ma_percent_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 52-Wk High ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_fiftytwo_week_high {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_fiftytwo_week_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 52-Wk Low ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_fiftytwo_week_low {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_fiftytwo_week_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 52-Wk Range ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_fiftytwo_week_range {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_fiftytwo_week_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Float Shares ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_float_shares {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_float_shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High Limit ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_high_limit {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_high_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holdings Gain ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_holdings_gain {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_holdings_gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gain &amp; % Gain ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_holdings_gain_and_percent {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_holdings_gain_and_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holdings % Gain ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_holdings_percent_gain {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_holdings_percent_gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mkt Value ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_holdings_value {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_holdings_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd Size ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_last_trade_size {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_last_trade_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low Limit ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_low_limit {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_low_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mkt Cap ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_market_cap {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_market_cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More Info ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_more_info {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_name {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1-Yr Trgt Price ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_one_year_target {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_one_year_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_open {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P/E ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pe_ratio {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pe_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die P/E Next Yr ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pe_ratio_next_year {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pe_ratio_next_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PEG Ratio ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_peg_ratio {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_peg_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_percent_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_percent_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Chg from 52-Wk Low ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_percent_change_fiftytwo_week_high {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_percent_change_fiftytwo_week_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Chg from 52-Wk High ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_percent_change_fiftytwo_week_low {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_percent_change_fiftytwo_week_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd Time &amp; Price (Pre/Aft Mkt) ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_after_mkt_price_and_time {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_after_mkt_price_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pre Mkt Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_mkt_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_mkt_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pre Mkt Chg &amp; % ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_mkt_change_and_percent {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_mkt_change_and_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pre Mkt % Chg ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_mkt_percent_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_mkt_percent_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd (Pre Mkt) ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_mkt_price {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_mkt_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd Time &amp; Price (Pre Mkt) ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_mkt_price_and_time {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_mkt_price_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Trd Time (Pre Mkt) ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_pre_mkt_time {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_pre_mkt_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prev Close ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_prev_close {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_prev_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time &amp; Price ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price_and_time {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price_and_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price Paid ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price_paid {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price/Book ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price_per_book {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price_per_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price/EPS Est Curr Yr ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price_per_eps_est_current_year {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price_per_eps_est_current_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price/EPS Est Next Yr ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price_per_eps_est_next_year {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price_per_eps_est_next_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price/Sales ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_price_per_sales {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_price_per_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shares Out ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_shares_out {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_shares_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shares ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_shares_owned {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_shares_owned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Ratio ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_short_ratio {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_short_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chart ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_sparkline {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_sparkline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symbol ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_symbol {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_time {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trd Date ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_trade_date {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_trade_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 200-Day MA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_twohundred_day_ma {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_twohundred_day_ma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chg from 200-Day MA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_twohundred_day_ma_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_twohundred_day_ma_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Chg from 200-Day MA ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_twohundred_day_ma_percent_change {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_twohundred_day_ma_percent_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        internal static string fin_pf_viewColumn_volume {
            get {
                return ResourceManager.GetString("fin_pf_viewColumn_volume", resourceCulture);
            }
        }
    }
}
